/**
 * Daysight — Email Deliverability Configuration
 *
 * This module defines the email infrastructure settings used by the sending
 * layer (Resend in production). It also serves as living documentation of the
 * DNS records and compliance requirements the operator must set up before any
 * public traffic hits the system.
 *
 * In the prototype, this is consumed by email-preview.html to show realistic
 * email headers. In production, the Resend integration reads from these values
 * (or their environment-variable equivalents).
 */

const EmailConfig = (() => {

  // ── Sending identity ────────────────────────────────────────────────────────
  const sending = {
    fromName:    'Daysight',
    fromAddress: 'reminders@mail.daysight.xyz',  // subdomain, NOT root
    replyTo:     'support@daysight.xyz',
    returnPath:  'bounces@mail.daysight.xyz',     // for bounce handling
    domain:      'daysight.xyz',
    sendingSubdomain: 'mail.daysight.xyz',        // isolate transactional reputation
  };

  // ── DNS records (operator must create these before launch) ──────────────────
  //
  // SPF  — authorizes Resend's IPs to send on behalf of mail.daysight.xyz
  // DKIM — signs outgoing mail so receivers can verify it hasn't been tampered
  // DMARC — tells receivers what to do with mail that fails SPF/DKIM
  //
  // These are the *values* to put in your DNS provider (Cloudflare, Route 53,
  // Namecheap, etc.). The exact Resend DKIM keys are generated when you verify
  // your domain in the Resend dashboard — replace the placeholder below.
  //
  const dns = {
    spf: {
      type: 'TXT',
      host: 'mail.daysight.xyz',
      value: 'v=spf1 include:amazonses.com ~all',
      note: 'Resend sends via Amazon SES. Update if Resend changes infrastructure.',
    },
    dkim: [
      {
        type: 'CNAME',
        host: 'resend._domainkey.mail.daysight.xyz',
        value: '*** REPLACE: paste the CNAME value from Resend dashboard ***',
        note: 'Generated by Resend when you add mail.daysight.xyz as a sending domain.',
      },
    ],
    dmarc: {
      type: 'TXT',
      host: '_dmarc.daysight.xyz',
      value: 'v=DMARC1; p=quarantine; rua=mailto:dmarc-reports@daysight.xyz; pct=100; adkim=s; aspf=s',
      note: 'Start at p=quarantine for the first 2 weeks, then move to p=reject once volume is stable and no legitimate mail is failing.',
    },
    returnPath: {
      type: 'CNAME',
      host: 'bounces.mail.daysight.xyz',
      value: '*** REPLACE: paste the Return-Path CNAME from Resend ***',
      note: 'Enables custom Return-Path alignment for SPF. Resend provides this.',
    },
  };

  // ── Email headers (applied to every outgoing message) ──────────────────────
  //
  // These headers improve deliverability and comply with Gmail/Yahoo bulk-sender
  // requirements (effective Feb 2024).
  //
  const headers = {
    'List-Unsubscribe':      '<https://daysight.xyz/unsubscribe?token={{unsubscribe_token}}>, <mailto:unsubscribe@daysight.xyz?subject=Unsubscribe-{{user_id}}>',
    'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
    'Feedback-ID':           '{{reminder_type}}:{{partner}}:landmarks',
    'X-Entity-Ref-ID':       '{{reminder_id}}',
    'X-Mailer':              'Daysight/1.0 (Resend)',
    'Precedence':            'bulk',
  };

  // ── Compliance checklist (shown in admin panel) ────────────────────────────
  const complianceChecklist = [
    { id: 'spf',           label: 'SPF record published',                   status: 'pending', category: 'dns' },
    { id: 'dkim',          label: 'DKIM CNAME verified in Resend',          status: 'pending', category: 'dns' },
    { id: 'dmarc',         label: 'DMARC record published (p=quarantine)',  status: 'pending', category: 'dns' },
    { id: 'return_path',   label: 'Custom Return-Path CNAME set',          status: 'pending', category: 'dns' },
    { id: 'subdomain',     label: 'Sending from subdomain (mail.*)',        status: 'done',    category: 'infra' },
    { id: 'list_unsub',    label: 'List-Unsubscribe + One-Click header',   status: 'done',    category: 'headers' },
    { id: 'feedback_id',   label: 'Feedback-ID header for Gmail Postmaster',status: 'done',    category: 'headers' },
    { id: 'warmup',        label: 'IP warmup plan (ramp over 2 weeks)',     status: 'pending', category: 'infra' },
    { id: 'postmaster',    label: 'Google Postmaster Tools enrolled',       status: 'pending', category: 'monitoring' },
    { id: 'snds',          label: 'Microsoft SNDS enrolled',                status: 'pending', category: 'monitoring' },
    { id: 'bounce_handler',label: 'Webhook for bounces → suppress list',   status: 'pending', category: 'infra' },
    { id: 'complaint_handler', label: 'Webhook for spam complaints → auto-unsub', status: 'pending', category: 'infra' },
  ];

  // ── IP warmup schedule ─────────────────────────────────────────────────────
  //
  // Resend handles shared-IP warmup automatically, but if Daysight graduates
  // to a dedicated IP (at ~50k+ sends/month), follow this ramp:
  //
  const warmupSchedule = [
    { day: 1,  dailyLimit: 50,   note: 'Seed with engaged users only (team + beta testers)' },
    { day: 2,  dailyLimit: 100,  note: 'Still engaged-only' },
    { day: 3,  dailyLimit: 200,  note: '' },
    { day: 4,  dailyLimit: 500,  note: 'Monitor Postmaster Tools after this point' },
    { day: 5,  dailyLimit: 1000, note: '' },
    { day: 7,  dailyLimit: 2000, note: 'Check bounce rate — must be < 2%' },
    { day: 10, dailyLimit: 5000, note: 'Check spam complaint rate — must be < 0.1%' },
    { day: 14, dailyLimit: 10000,note: 'Full volume unlocked if rates are clean' },
  ];

  // ── Monitoring thresholds ──────────────────────────────────────────────────
  const thresholds = {
    bounceRateMax:    0.02,   // 2% — above this, pause and investigate
    complaintRateMax: 0.001,  // 0.1% — Gmail's published threshold
    openRateMin:      0.20,   // if below 20%, something is wrong (deliverability or subject lines)
  };

  return { sending, dns, headers, complianceChecklist, warmupSchedule, thresholds };
})();
